// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_first_claim
NumericVector rcpp_first_claim(std::vector<int> id, std::vector<int> claim);
RcppExport SEXP _underwriter_rcpp_first_claim(SEXP idSEXP, SEXP claimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type id(idSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type claim(claimSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_first_claim(id, claim));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_uniq_day
NumericVector rcpp_uniq_day(StringMatrix id, NumericVector from, NumericVector to);
RcppExport SEXP _underwriter_rcpp_uniq_day(SEXP idSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringMatrix >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_uniq_day(id, from, to));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_underwriter_rcpp_first_claim", (DL_FUNC) &_underwriter_rcpp_first_claim, 2},
    {"_underwriter_rcpp_uniq_day", (DL_FUNC) &_underwriter_rcpp_uniq_day, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_underwriter(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
