// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_first_claim
NumericVector rcpp_first_claim(std::vector<double> claim, std::vector<double> id);
RcppExport SEXP _underwriter_rcpp_first_claim(SEXP claimSEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type claim(claimSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_first_claim(claim, id));
    return rcpp_result_gen;
END_RCPP
}
// regmatch
StringVector regmatch(std::string m, std::vector<std::string> x);
RcppExport SEXP _underwriter_regmatch(SEXP mSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type m(mSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(regmatch(m, x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_unique_day
NumericVector rcpp_unique_day(StringMatrix id, NumericVector from, NumericVector to);
RcppExport SEXP _underwriter_rcpp_unique_day(SEXP idSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringMatrix >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_unique_day(id, from, to));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_underwriter_rcpp_first_claim", (DL_FUNC) &_underwriter_rcpp_first_claim, 2},
    {"_underwriter_regmatch", (DL_FUNC) &_underwriter_regmatch, 2},
    {"_underwriter_rcpp_unique_day", (DL_FUNC) &_underwriter_rcpp_unique_day, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_underwriter(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
