# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

first_claim <- function(id, claim) {
    .Call(`_underwriter_first_claim`, id, claim)
}

rcpp_uniq_day <- function(id, from, to) {
    .Call(`_underwriter_rcpp_uniq_day`, id, from, to)
}

