# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_first_claim <- function(claim, id) {
    .Call(`_underwriter_rcpp_first_claim`, claim, id)
}

rcpp_unique_day <- function(id, from, to) {
    .Call(`_underwriter_rcpp_unique_day`, id, from, to)
}

